"""empty message

Revision ID: 3766fb9b2d84
Revises: 
Create Date: 2023-06-07 14:43:00.559839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3766fb9b2d84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idGame')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idGame', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'game', ['idGame'], ['id'])

    # ### end Alembic commands ###
