"""empty message

Revision ID: 7bf7e225d75f
Revises: f3577c7ec89e
Create Date: 2023-06-05 20:17:54.069803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf7e225d75f'
down_revision = 'f3577c7ec89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DateCreation', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('DateCreation')

    # ### end Alembic commands ###
