"""empty message

Revision ID: 973bdb497fb1
Revises: 6e04a1a684ab
Create Date: 2023-06-06 14:52:05.109455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973bdb497fb1'
down_revision = '6e04a1a684ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Modid', sa.Integer(), nullable=True),
    sa.Column('AuthorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AuthorId'], ['user.id'], name=op.f('fk_mod_download_AuthorId_user')),
    sa.ForeignKeyConstraint(['Modid'], ['mod.id'], name=op.f('fk_mod_download_Modid_mod')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mod_download'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_download')
    # ### end Alembic commands ###
