"""empty message

Revision ID: 9b2878864c23
Revises: 9f9ef65b377e
Create Date: 2023-05-31 14:31:07.383583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2878864c23'
down_revision = '9f9ef65b377e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Sex',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Sex',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
