"""empty message

Revision ID: 9bd916e37f35
Revises: f06d248123c5
Create Date: 2023-06-01 15:33:47.181790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd916e37f35'
down_revision = 'f06d248123c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GameId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('AuthorId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('GameTagId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'game', ['GameId'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['AuthorId'], ['id'])
        batch_op.create_foreign_key(None, 'game_tags', ['GameTagId'], ['id'])

    with op.batch_alter_table('mod_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('MessageAuthorId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['MessageAuthorId'], ['id'])
        batch_op.create_foreign_key(None, 'mod', ['Modid'], ['id'])

    with op.batch_alter_table('mod_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mod', ['Modid'], ['id'])

    with op.batch_alter_table('mod_picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mod', ['Modid'], ['id'])

    with op.batch_alter_table('mod_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mod', ['Modid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Modid')

    with op.batch_alter_table('mod_picture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Modid')

    with op.batch_alter_table('mod_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Modid')

    with op.batch_alter_table('mod_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('MessageAuthorId')
        batch_op.drop_column('Modid')

    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('GameTagId')
        batch_op.drop_column('AuthorId')
        batch_op.drop_column('GameId')

    # ### end Alembic commands ###
