"""empty message

Revision ID: a3bb320b2ae3
Revises: 9b2878864c23
Create Date: 2023-05-31 15:24:28.980453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bb320b2ae3'
down_revision = '9b2878864c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('Picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('Picture', sa.LargeBinary(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(), nullable=True),
    sa.Column('DateSend', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_video')
    op.drop_table('mod_picture')
    op.drop_table('mod_link')
    op.drop_table('mod_comment')
    op.drop_table('mod')
    op.drop_table('game')
    # ### end Alembic commands ###
