"""empty message

Revision ID: a58e43ae2a1a
Revises: 7bf7e225d75f
Create Date: 2023-06-06 14:10:27.691078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58e43ae2a1a'
down_revision = '7bf7e225d75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_vievs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Modid', sa.Integer(), nullable=True),
    sa.Column('AuthorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AuthorId'], ['user.id'], name=op.f('fk_mod_vievs_AuthorId_user')),
    sa.ForeignKeyConstraint(['Modid'], ['mod.id'], name=op.f('fk_mod_vievs_Modid_mod')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mod_vievs'))
    )
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DescriptionCard', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('DescriptionCard')

    op.drop_table('mod_vievs')
    # ### end Alembic commands ###
