"""empty message

Revision ID: f06d248123c5
Revises: a3bb320b2ae3
Create Date: 2023-06-01 14:45:35.971806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06d248123c5'
down_revision = 'a3bb320b2ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('Language')

    op.drop_table('game_tags')
    # ### end Alembic commands ###
