"""empty message

Revision ID: f3577c7ec89e
Revises: 9bd916e37f35
Create Date: 2023-06-05 19:51:52.213732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3577c7ec89e'
down_revision = '9bd916e37f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idGame', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_tags_idGame_game'), 'game', ['idGame'], ['id'])

    with op.batch_alter_table('mod_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LinkName', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_link', schema=None) as batch_op:
        batch_op.drop_column('LinkName')

    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_tags_idGame_game'), type_='foreignkey')
        batch_op.drop_column('idGame')

    # ### end Alembic commands ###
